# Generated by Django 5.0.7 on 2024-07-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contraseña',
            field=models.CharField(default=224, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='1@email.com', max_length=50),
            preserve_default=False,
        ),
    ]
