# Generated by Django 5.1 on 2024-08-21 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_home', '0009_remove_coupon_store_remove_invoice_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stockquantity', models.IntegerField()),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='a_home.image')),
            ],
        ),
    ]
