# Generated by Django 5.1 on 2024-09-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='bannerurl',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='logourl',
            new_name='horario',
        ),
    ]
