# Generated by Django 5.1 on 2024-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SIN', 'Sin categoría'), ('LIB', 'Libros'), ('TEC', 'Tecnología'), ('JAR', 'Jardinería'), ('ROP', 'Ropa'), ('HOG', 'Hogar'), ('ELE', 'Electrónicos'), ('DEP', 'Deportes'), ('JUG', 'Juguetes'), ('ORD', 'Ordenadores y Accesorios'), ('MOV', 'Móviles y Accesorios'), ('COS', 'Cosmética y Belleza'), ('SAL', 'Salud y Cuidado Personal'), ('ALM', 'Alimentos y Bebidas'), ('BEB', 'Bebés y Niños'), ('AUT', 'Automóviles y Motocicletas'), ('MUS', 'Música e Instrumentos Musicales'), ('VID', 'Videojuegos'), ('PEL', 'Películas y Series'), ('MAS', 'Mascotas y Animales'), ('OFI', 'Oficina y Papelería'), ('HERR', 'Herramientas y Mejoras del Hogar'), ('CAL', 'Calzado'), ('REC', 'Recreación al Aire Libre'), ('JOY', 'Joyas y Relojes'), ('VIA', 'Viajes y Equipaje'), ('ART', 'Arte y Manualidades'), ('JUE', 'Juegos de Mesa y Puzzles')], default='SIN', max_length=5),
        ),
    ]
