# Generated by Django 5.1 on 2024-08-21 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discounttype', models.TextField(max_length=1255)),
                ('discountvalue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
