# Generated by Django 5.1 on 2024-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0006_alter_chatmessage_messagecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='apellido', max_length=400),
            preserve_default=False,
        ),
    ]
