# Generated by Django 5.1 on 2024-09-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0009_remove_coupon_store_remove_invoice_order_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dirección',
            field=models.TextField(max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='horario',
            field=models.TextField(max_length=1255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='imageStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_images', to='a_home.image'),
        ),
    ]
