# Generated by Django 5.1 on 2024-09-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0009_remove_coupon_store_remove_invoice_order_and_more'),
        ('a_users', '0003_subscriptionplan_remove_profile_contraseña_and_more'),
        ('stores', '0002_store_dirección_store_horario_store_imagestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='bannerurl',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logourl',
        ),
        migrations.AddField(
            model_name='store',
            name='bannerImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_banner_images', to='a_home.image'),
        ),
        migrations.AddField(
            model_name='store',
            name='logoImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_logo_images', to='a_home.image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile'),
        ),
    ]
