# Generated by Django 5.1 on 2024-08-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0005_image_alter_article_content_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='messagecontent',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, max_length=1255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.TextField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(max_length=1255),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnailurl',
            field=models.TextField(max_length=1255, null=True),
        ),
    ]
