# Generated by Django 5.1 on 2024-09-06 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0009_remove_coupon_store_remove_invoice_order_and_more'),
        ('a_users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='a_users.profile'),
            preserve_default=False,
        ),
    ]
