# Generated by Django 5.1 on 2024-09-06 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_home', '0010_image_user'),
        ('a_users', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='a_users.profile'),
        ),
    ]
