# Generated by Django 5.1 on 2024-08-21 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_contraseña_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planname', models.CharField(max_length=200, unique=True)),
                ('storagelimit', models.IntegerField()),
                ('features', models.TextField(max_length=1255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='temporal', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='11111111111', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('createdat', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedat', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.subscriptionplan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_users.profile')),
            ],
        ),
    ]
