# Generated by Django 5.1 on 2024-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_subscriptionplan_remove_profile_contraseña_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='Smith', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default='Bob', max_length=200),
            preserve_default=False,
        ),
    ]
